package HRSystem;


/**
* HRSystem/HRInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HRSystem.idl
* Tuesday, November 13, 2018 8:46:24 o'clock PM EST
*/

abstract public class HRInterfaceHelper
{
  private static String  _id = "IDL:HRSystem/HRInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, HRSystem.HRInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HRSystem.HRInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (HRSystem.HRInterfaceHelper.id (), "HRInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HRSystem.HRInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_HRInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HRSystem.HRInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static HRSystem.HRInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof HRSystem.HRInterface)
      return (HRSystem.HRInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      HRSystem._HRInterfaceStub stub = new HRSystem._HRInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static HRSystem.HRInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof HRSystem.HRInterface)
      return (HRSystem.HRInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      HRSystem._HRInterfaceStub stub = new HRSystem._HRInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
