package HRSystem;


/**
* HRSystem/HRInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HRSystem.idl
* Tuesday, November 13, 2018 8:46:24 o'clock PM EST
*/

public interface HRInterface extends HRInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HRInterface
