package HRSystem;


/**
* HRSystem/HRInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HRSystem.idl
* Tuesday, November 13, 2018 8:46:24 o'clock PM EST
*/

public abstract class HRInterfacePOA extends org.omg.PortableServer.Servant
 implements HRSystem.HRInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createMRecord", new java.lang.Integer (0));
    _methods.put ("createERecord", new java.lang.Integer (1));
    _methods.put ("EditRecord", new java.lang.Integer (2));
    _methods.put ("getRecordCounts", new java.lang.Integer (3));
    _methods.put ("transferRecord", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // HRSystem/HRInterface/createMRecord
       {
         String managerID = in.read_string ();
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         int employeeID = in.read_long ();
         org.omg.CORBA.StringHolder mailID = new org.omg.CORBA.StringHolder ();
         mailID.value = in.read_string ();
         HRSystem.ProjectHolder project = new HRSystem.ProjectHolder ();
         project.value = HRSystem.ProjectHelper.read (in);
         String location = in.read_string ();
         String $result = null;
         $result = this.createMRecord (managerID, firstName, lastName, employeeID, mailID, project, location);
         out = $rh.createReply();
         out.write_string ($result);
         out.write_string (mailID.value);
         HRSystem.ProjectHelper.write (out, project.value);
         break;
       }

       case 1:  // HRSystem/HRInterface/createERecord
       {
         String managerID = in.read_string ();
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         int employeeID = in.read_long ();
         org.omg.CORBA.StringHolder mailID = new org.omg.CORBA.StringHolder ();
         mailID.value = in.read_string ();
         org.omg.CORBA.StringHolder projectID = new org.omg.CORBA.StringHolder ();
         projectID.value = in.read_string ();
         String $result = null;
         $result = this.createERecord (managerID, firstName, lastName, employeeID, mailID, projectID);
         out = $rh.createReply();
         out.write_string ($result);
         out.write_string (mailID.value);
         out.write_string (projectID.value);
         break;
       }

       case 2:  // HRSystem/HRInterface/EditRecord
       {
         String managerID = in.read_string ();
         String recordID = in.read_string ();
         String fieldName = in.read_string ();
         org.omg.CORBA.StringHolder newValue = new org.omg.CORBA.StringHolder ();
         newValue.value = in.read_string ();
         String $result = null;
         $result = this.EditRecord (managerID, recordID, fieldName, newValue);
         out = $rh.createReply();
         out.write_string ($result);
         out.write_string (newValue.value);
         break;
       }

       case 3:  // HRSystem/HRInterface/getRecordCounts
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.getRecordCounts (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // HRSystem/HRInterface/transferRecord
       {
         String managerID = in.read_string ();
         String recordID = in.read_string ();
         String remoteCenterServerName = in.read_string ();
         String $result = null;
         $result = this.transferRecord (managerID, recordID, remoteCenterServerName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:HRSystem/HRInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public HRInterface _this() 
  {
    return HRInterfaceHelper.narrow(
    super._this_object());
  }

  public HRInterface _this(org.omg.CORBA.ORB orb) 
  {
    return HRInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class HRInterfacePOA
