package HRSystem;


/**
* HRSystem/HRInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HRSystem.idl
* Tuesday, November 13, 2018 8:46:24 o'clock PM EST
*/

public interface HRInterfaceOperations 
{
  String createMRecord (String managerID, String firstName, String lastName, int employeeID, org.omg.CORBA.StringHolder mailID, HRSystem.ProjectHolder project, String location);
  String createERecord (String managerID, String firstName, String lastName, int employeeID, org.omg.CORBA.StringHolder mailID, org.omg.CORBA.StringHolder projectID);
  String EditRecord (String managerID, String recordID, String fieldName, org.omg.CORBA.StringHolder newValue);
  String getRecordCounts (String managerID);
  String transferRecord (String managerID, String recordID, String remoteCenterServerName);
} // interface HRInterfaceOperations
