package HRSystem;


/**
* HRSystem/Project.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HRSystem.idl
* Saturday, October 20, 2018 10:25:51 o'clock PM EDT
*/

public final class Project implements org.omg.CORBA.portable.IDLEntity
{
  public String projectID = null;
  public String clientName = null;
  public String projectName = null;

  public Project ()
  {
  } // ctor

  public Project (String _projectID, String _clientName, String _projectName)
  {
    projectID = _projectID;
    clientName = _clientName;
    projectName = _projectName;
  } // ctor
  
  public String getProjectID() {
		return projectID;
	}
	public void setProjectID(String projectID) {
		this.projectID = projectID;
	}
	public String getClientName() {
		return clientName;
	}
	public void setClientName(String clientName) {
		this.clientName = clientName;
	}
	public String getProjectName() {
		return projectName;
	}
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

} // class Project
