package HRSystem;

/**
* HRSystem/ProjectHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HRSystem.idl
* Tuesday, November 13, 2018 8:46:24 o'clock PM EST
*/

public final class ProjectHolder implements org.omg.CORBA.portable.Streamable
{
  public HRSystem.Project value = null;

  public ProjectHolder ()
  {
  }

  public ProjectHolder (HRSystem.Project initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HRSystem.ProjectHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HRSystem.ProjectHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HRSystem.ProjectHelper.type ();
  }

}
